### ISSUE TITLE
Flatpak Progress

### ISSUE THREAD

**Issue by LeSnake04** [mtkennerly/ludusavi#96]
For anyone strawling by: the flatpak is done and available on all app store supporting flatpak and via
```
flatpak install ludusavi
```

There just some minor cosmetic changes for the storefront to be done, the package itself is ready for use.

# Open Questions
 - [x] Internet access needed ? - yes
 - [x] Sound needed ? - no
 - [x] xdg desktop portal support ? – Irrelevant
 - [x] following releases tag or master branch? - releases
 - [x] notifications? - no

#  TODO 
## Things that should be merged with main repo
When will they be able to be merged?
- [x] desktop file
- [x] ~~generated-sources – needs to be in repo for auto-updating flatpak, but can be provided via flathub repo without automated updates.~~Auto-Update Not realisticly possible
- [x] metainfo

## general
- [x] desktop file

## yaml
- [x] Base structure
- [x] add rust sdk
- [x] ~~auto updating of release tag~~ not possible
- [x] get cargo build to work – genrated sources needed
- [x] move binary
- [x] move desktop file
- [x] move icons
- [x] compiles
- [x] cli works
- [x] gui

## metainfo
- [x] base structure
- [x] description
- [x] OARS Rating – Internet needed ? – https://hughsie.github.io/oars/generate.html
- [x] desktop file
- [x] Screenshots

### read access
- [x] All? Should be avoided if possible – xdg desktop portal question releveant
- [x] steam flatpak
- [x] steam

## write access
- [x] ~/lududusavi-backup 
- [x] Everywhere

**Comment by LeSnake04** [comment]
Note: for oars internet doesn't matter because this app isn't a social app.

**Comment by LeSnake04** [comment]
@mtkennerly I need some info regarding open questions and what files you can put into the main repo.

**Comment by mtkennerly** [comment]
This sounds great! Thanks for working on this.

>  Internet access needed ?

* At install time: no.
* At runtime: yes (to check for manifest updates).

> Sound needed ?

No.

> xdg desktop portal support ?

I'm not familiar with this. Would it require something like [ashpd](https://docs.rs/ashpd/0.3.0/ashpd/index.html), or is there a way for Flatpak to support normal file system access calls?

> following releases tag or master branch?

It should definitely follow the releases. Master may not always be usable, even though it should be most of the time.

>  generated-sources – needs to be in repo for auto-updating flatpak, but can be provided via flathub repo without automated updates.

I'm assuming most people would want it on Flathub for standardization and discoverability, right? If the GitHub build produces the necessary files, I don't mind taking them and manually running a publish command when there's a new release.

>  All? Should be avoided if possible – xdg desktop portal question releveant

Technically, it should be all, since you can configure arbitrary paths as roots and in custom game locations. The absolute bare minimum would be:

* `~`
* `$XDG_DATA_HOME`
* `$XDG_CONFIG_HOME`

> I figure out a way how to convert it while building the flatpak (I am not sure if its possible and it will increase the complexity and build time)

The ideal option would be some command that runs automatically as part of the GitHub build. The next best option would be some command that I can run manually when there's a new release.

**Comment by LeSnake04** [comment]
xdg portals means the app can request access to files and folders through the desktop file manager and as flatpaks get access to data outside the configured folders. 

Once i get the GUI to work, i will see if its supports xdg portals. If it has no support its ok, most flatpaks dont support it (even major ones like firefox or steam). But if it has support already its great and makes it a bit easier.
I assume for anything but the backup dir I can mark it as read only

Especially regarding external drives, which can be hassle with flatpaks.

Also I forgot to ask, does it use notifications?

**Comment by LeSnake04** [comment]
Regarding the generated sources –its needed so flatpak knows what to download since during compiling the flatpak its cut of from the internet

That means somewhere during the update process this needs to be run:  https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo:
`python3 ./flatpak-cargo-generator.py Cargo.lock -o cargo-sources.json`

The flatpak needs that json, so eighter it needs to be genrated automatically  (in the flatpak repo or the main repo) or one of us needs to generate it every new release

**Comment by mtkennerly** [comment]
> I assume for anything but the backup dir I can mark it as read only

You can also restore a backup to the original paths, so everything is read/write, unfortunately 😅 

> Also I forgot to ask, does it use notifications?

Nope, no OS notifications.

> The flatpak needs that json, so eighter it needs to be genrated automatically (in the flatpak repo or the main repo) or one of us needs to generate it every new release

It should be easy enough to generate automatically during a GitHub build. I'm fine with it happening during the Ludusavi build or another repo's build - whichever way's easier.

**Comment by LeSnake04** [comment]
Firstly,
Right, I somehow totally forgot about storage access on restoring. ^^

So there is no way around giving it acess to everything. 
Even if it has xdg portals support, since xdg portals only give temporary access. They are mainly intended for editors like gimp or libreoffice, which only needs access for files explicitly opened and need a file chooser anyway. They might work for custom paths but not for permanent and silent access to external data sources.

Sorry for being a bit obnoxious but the flathub team tries to minimize the folder access, especially for new apps, so I needed arguments for explaining why this one needs so broad access.

Secondly,
Its just downloading a python script and running it.

I think its way easier to start the script via a github action on your side. It may be possible via the flatpak, but requires extra steps because of the way flatpaks are build

**Comment by LeSnake04** [comment]
I am on holiday for the next days so the progress will be slow for a few days

**Comment by LeSnake04** [comment]
The GUI crashes instantly for some reason. I assume based on the dependencies there is no logging that could help fixing it?

**Comment by mtkennerly** [comment]
Does it print anything at all in the console? You could try running it with the `RUST_BACKTRACE` environment variable set to `1`.

Here's a debug build with `simple_logger` added:

[ludusavi-ec73cbdc26c8c1564af30ab0b9874e8c4fb74856-logging.zip](https://github.com/mtkennerly/ludusavi/files/8508226/ludusavi-ec73cbdc26c8c1564af30ab0b9874e8c4fb74856-logging.zip)

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 6d19926..cce9402 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -28,6 +28,7 @@ reqwest = { version = "0.10.6", features = ["blocking", "rustls-tls"], default-f
 serde = { version = "1.0.111", features = ["derive"] }
 serde_json = "1.0.57"
 serde_yaml = "0.8.13"
+simple_logger = "2.1.0"
 structopt = "0.3.15"
 thiserror = "1.0.20"
 walkdir = "2.3.1"
diff --git a/src/main.rs b/src/main.rs
index a3514a2..885e1ac 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -13,6 +13,7 @@ mod shortcuts;
 mod registry;
 
 fn main() {
+    simple_logger::SimpleLogger::new().init().unwrap();
     prelude::migrate_legacy_config();
 
     let args = cli::parse_cli();
```

**Comment by LeSnake04** [comment]
No output even with RUST_BACKTRACE...

And you build is an exe, so I cannot use it.
I will just make a simple fork tomorrow, add logging there and see if the log helps (having it on a repo is way easier to test anyway and I dont wanna force you to add commits just for this.) That way I can also try applying potentional minor fixes and prepare my pull request with the apdata, desktop file etc.

When It works on my repo I will push a pull request to yours and change the urls in the flatpak builder.

**Comment by mtkennerly** [comment]
Oh, duh, I don't know why I didn't realize I needed to give you a Linux build 😅 Sorry about that.

**Comment by mtkennerly** [comment]
A fork would definitely be good, but here's a proper Linux build with logging in the meantime. I was going to give you a debug build, but it was too big for GitHub to let me attach it, so it's a release build instead:

[ludusavi-v0.10.0-post.11+9e5cf6e-linux.zip](https://github.com/mtkennerly/ludusavi/files/8508731/ludusavi-v0.10.0-post.11%2B9e5cf6e-linux.zip)

**Comment by LeSnake04** [comment]
FIXED IT!

Turns out this had nothing to do with libraries, I just didn't realized there was a permission needed for GPU acceleration.

**Comment by LeSnake04** [comment]
Its basically done, I just need to get the desktop icon to work. I am trying to fix it  within the next weeks (I dont have acess to my main pc for the next 2-3 weeks)

Also auto update is not realisticly possible since cargo isnt properly integrated in flatpak yet. So I will have to update the flatpak whenever there is a new release

**Comment by psymin** [comment]
Thanks for working on this flatpak, I think it will be quite useful for Steam Deck users.

Especially if it has this environment variable set as per the linked issue:

WINIT_X11_SCALE_FACTOR=1

https://github.com/mtkennerly/ludusavi/issues/91#issuecomment-1197671483

**Comment by LeSnake04** [comment]
@psymin: done

@mtkennerly :
About the extra files, that should be merged: can you push single commmits to the tag 0.10.0 (without all the other commits) or do we need to wait for the next release and I add the files untill then?

**Comment by mtkennerly** [comment]
@LeSnake04 Although Git/GitHub allow it, I don't think it's a good idea to change the content of a tag for an existing release. One option would be:

* I create a `release/v0.10.0-flatpak` branch that matches the `v0.10.0` tag
* You open a PR to add the files to that branch (the `assets` folder would be good)
* I create a `v0.10.0-flatpak` tag
* I merge that branch into master so the files can be updated for future releases

I've gone ahead and created the branch, but do you know if this could interfere with Flatpak's `x-checker-data` behavior? `v0.10.0-flatpak` would *just* be a tag without an associated GitHub release.

**Comment by LeSnake04** [comment]
I should probably comment out x-checher-data anyway because of the generated sources situation (the generation makes it very hard to auto update untill cargo become a integrated module type), so the tag needs to be updated manually. 

So this would absolutely work

**Comment by LeSnake04** [comment]
It works! 

you can install it with this command: ```flatpak install --user https://dl.flathub.org/build-repo/102242/com.github.mtkennerly.ludusavi.flatpakref```

You might net to reinstall it with ```flatpak install --user com.github.mtkennerly.ludusavi``` once its published to get updates.

**Comment by psymin** [comment]
Yep, it does seem to work on the Steam Deck in Desktop and Game mode.

**Comment by LeSnake04** [comment]
@psymin and the scale is correct as well?

**Comment by psymin** [comment]
Yep.  Now I'm looking forward to cloud support ;)

**Comment by LeSnake04** [comment]
@psymin

Do you happen to know where the steam deck  mounts the sd card?

**Comment by LeSnake04** [comment]
I restricted the flatpak to the home directory and /run/media/. 

Interestingly I just realised, that when I click an folder Icon, it opens the desktop-portal file chooser. Seems like Iced uses xdg-desktop-portal. This is good to know for potential future flatpaks with iced projects.

But I am pretty sure this cant be used too much in this case, since the code will refer to the native path, while the paths gereted by the desktop portal are be different, so it will still write acess to the entire home folder for restoring files without save to dialog and, but this will likely work for specifing backup targets to external drives easily.

Though in order to read and write saves from/to external drives outside /run/media/ the user will be required to add acess to the mount path for the flatpak. 

![Screenshot_20220812_154227](https://user-images.githubusercontent.com/47243761/184366097-96550c38-cbe8-4e1e-abef-bc8e4823706d.png)

**Comment by psymin** [comment]
> 

The default SD card path is `/run/media/mmcblk0p1`

A slightly related note:
In Desktop mode the file chooser works properly, and I can "Add root" paths.

In Game Mode I'm not seeing a file chooser UI when attempting to "Add root".  Not a huge issue since the paths can easily be added in desktop mode.

**Comment by LeSnake04** [comment]
can you please test again with this version?

```flatpak install --user https://dl.flathub.org/build-repo/102371/com.github.mtkennerly.ludusavi.flatpakref```

**Comment by psymin** [comment]
The UI appears to function the same as before in both Desktop and Game modes.

It is possible that I didn't accurately test it in Game mode previously.

**Comment by mtkennerly** [comment]
> Interestingly I just realised, that when I click an folder Icon, it opens the desktop-portal file chooser. Seems like Iced uses xdg-desktop-portal. This is good to know for potential future flatpaks with iced projects.

For folder browsing, Ludusavi uses [native-dialog](https://crates.io/crates/native-dialog), specifically [`native_dialog::FileDialog::new().show_open_single_dir()`](https://docs.rs/native-dialog/0.6.3/native_dialog/struct.FileDialog.html#method.show_open_single_dir). Looking at the [platform-specific implementation](https://github.com/balthild/native-dialog-rs/blob/d0f685745c2e3576f5f1b1262ab6c440ba85a99c/src/dialog_impl/gnu/file.rs#L62-L81), it can use KDialog or Zenity on Linux.

**Comment by LeSnake04** [comment]
@psymin ignore the file chooser stuff was just an observation following up on a previous discussion with mtkennerly.

**Comment by LeSnake04** [comment]
Here it is. https://flathub.org/apps/details/com.github.mtkennerly.ludusavi


@mtkennerly I noticed 2 thing: first flathub.org doesnt support plaiyng gifs, so we should use images instead, wich show the program properly. And the gui image should be shown first.

**Comment by mtkennerly** [comment]
@LeSnake04 Thanks! I also noticed some issues with the description text (first paragraph contains an unrendered `[Rust](https://www.rust-lang.org)` and everything after that paragraph is just `(null)`). It [sounds like](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description) `<b>` and nested `<ul>` are prohibited by the metainfo specification.

I've [pushed an update](https://github.com/mtkennerly/ludusavi/commit/0cbe9e2a935b485c98e8563978058b652480cb17) to the `release/v0.10.0-flatpak` branch, tagged it as `v0.10.0+flatpak2`, and [pushed a commit](https://github.com/flathub/com.github.mtkennerly.ludusavi/commit/494081c1d364f764ded0ddf5e6b72033af7322a1) to https://github.com/flathub/com.github.mtkennerly.ludusavi to reference that tag. Let's see how it looks when the build finishes.

**Comment by mtkennerly** [comment]
[The build succeeded](https://buildbot.flathub.org/#/builders/32/builds/105208), and I published it manually from the buildbot site, but I'm not seeing a change yet on the app listing. Not sure how long it normally takes to refresh.

**Comment by mtkennerly** [comment]
The listing has updated. Everything looks good, except that the CLI screenshot only shows the thumbnail correctly. When you scroll to it, the larger size shows an error. Any ideas what might cause that? Those screenshots are PNG.

> <img width="535" alt="image" src="https://user-images.githubusercontent.com/4934192/184991876-c8c4acc6-361b-4408-b5e3-c2ff49bedd86.png">

**Comment by LeSnake04** [comment]
I will ask the flathub staff about the picture.

I also noticed this:
https://github.com/mtkennerly/ludusavi/commit/0cbe9e2a935b485c98e8563978058b652480cb17?diff=unified#r81361943

**Comment by mtkennerly** [comment]
> PS: Sorry for the xml formatting errors, I haven't worked with xml/html in ages.

No worries! You've been a great help getting this done :)

Added a note about this to the README installation section.

**Comment by mtkennerly** [comment]
I've updated Flathub for 0.11.0. @LeSnake04 or @psymin, would you mind double checking to make sure it works okay?

**Comment by LeSnake04** [comment]
works for me.

**Comment by kalyway101** [comment]
So, I'm sure I'm just doing something incorrectly, but I have enabled all write file permissions for the Ludusavi flatpack via Flatseal, and Ludusavi seems to copy the folder structure properly, however, when it comes to the individual files, it hangs at the very end and doesn't seem to fully process for some reason. 

![image](https://user-images.githubusercontent.com/49223461/189167493-3f63c06d-2384-45ce-9ae6-36acdab18576.png)

I tried to search for some logs but was not able to see if any existed or not😅 I am a Steam Deck user

**Comment by mtkennerly** [comment]
@kalyway101 Does it also happen when restoring a single game, or just when restoring all of them? I'm curious if there's a specific path(s) that might be tripping it up. Could you also try running the command line to verify if it happens there as well? (`flatpak run com.github.mtkennerly.ludusavi restore 'GAME NAME HERE'`)

Unfortunately, there's no logging right now, but if the above doesn't help narrow it down, I can add some in a Flatpak beta build. Even if there's a permissions issue, Ludusavi should report the issue for each game that failed to restore, not just hang, so I'm not quite sure what's going wrong here.

**Comment by kalyway101** [comment]
@mtkennerly Ah, that makes sense why I could not find it then. 

`(deck@steamdeck ~)$ flatpak run com.github.mtkennerly.ludusavi restore "Marvel's Spider-Man Remastered"
Do you want to restore from /home/deck/quruc-f6ry9? yes
██████████████████████████████████████████████████████████████████████████████████████████████████████████ 1/1
`
It just sits here indefinitely after running the command. I did have redirects set up, but I removed those and let it choose the default location in `/home/deck/C_`. It does the same thing where it creates the folder structure but does not add any files. Interestingly, when my redirects were still setup, and after I attempted to run restore, _**some**_ a couple files were added, but it would hang and not do anything else as well. I also made sure I have ALL boxes checked in Flatseal under Filesystem.

**Comment by mtkennerly** [comment]
I've published a beta build with some logging. Would you mind giving it a try and posting the log here?

Install beta build:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta com.github.mtkennerly.ludusavi
```

Run test:

```
RUST_LOG=ludusavi=trace flatpak run com.github.mtkennerly.ludusavi//beta restore --force "Marvel's Spider-Man Remastered"
```

Grab log file: `ludusavi_rCURRENT.log` in `$XDG_CONFIG_HOME/ludusavi` (or `~/.config/ludusavi`)

**Comment by mtkennerly** [comment]
Oh yeah, I forgot. Done :D

**Comment by LeSnake04** [comment]
https://beta.flathub.org/apps/details/com.github.mtkennerly.ludusavi 

Its going pretty nicely.  10-40 installs per day.
